#!/bin/sh

infile=$1
outdir=`dirname $1`/NJ
outfile=$outdir/`basename $1 .aml`.sml

#echo $infile --> $outfile

if [ ! -d $outdir ]
then mkdir $outdir
fi

#sed 's/^import[^"]*"[^"]*"//g' $infile >$outfile
exec awk -f $0.awk $infile >$outfile
