#!/bin/sh

dir=`dirname $0`
dir=`(cd $dir && pwd)`

case `sml </dev/null | grep "110\.0\.[0-9]"` in
    *Jersey*)
	CM=cm
	;;
    *)
	CM=newcm
	;;
esac

case `uname -s` in
    CYGWIN*)
	AML2SML="sh \"$dir/aml2sml\""
	sml="cmd /c sml-cm"
	;;
    *)
	AML2SML=$dir/aml2sml
	sml=sml
	;;
esac

export AML2SML

cat `dirname $0`/alice-$CM.sml - | $sml
