#!/bin/sh

dir=`dirname $0`
dir=`(cd $dir && pwd)`

case `uname -s` in
    CYGWIN*)
	AML2SML="sh \"$dir/aml2sml\""
	sml="cmd /c sml-cm"
	;;
    *)
	AML2SML=$dir/aml2sml
	sml=sml
	;;
esac

export AML2SML

cat `dirname $0`/alice-cm.sml - | $sml
