#!/bin/sh

case `uname -s` in
    CYGWIN*)
	dir=`dirname $0`
	dir=`(cd $dir && pwd)`
	AML2SML="sh $dir/aml2sml"
	sml="cmd /c sml-cm"
	;;
    *)
	AML2SML=`dirname $0`/aml2sml
	sml=sml
	;;
esac

export AML2SML

cat `dirname $0`/alice-cm.sml - | $sml
