## -*- Makefile -*-
##
## Author:
##   Leif Kornstaedt <kornstae@ps.uni-sb.de>
## 
## Copyright:
##   Leif Kornstaedt, 2000-2003
## 
## Last change:
##   $Date$ by $Author$
##   $Revision$
## 

.PHONY: all clean veryclean distclean

%.$(OBJEXT): %.cc
	$(CXX) $(DEFINES) $(INCLUDES) $(CXXFLAGS) -c $< -o $@

%.s: %.cc
	$(CXX) $(DEFINES) $(INCLUDES) $(CXXFLAGS) -S $< -o $@
