# -*- makefile -*-

# The cvs target creates the autoconf/automake files that are necessary for
# the build but should better not be put under CVS control.
# 
# This is a temporary hack.

cvs:
	aclocal -I .
	autoconf
	libtoolize --ltdl
	automake --add-missing

.PHONY: cvs
