# -*- makefile -*-

# The cvs target creates the autoconf/automake files that are necessary for
# the build but should better not be put under CVS control.
# 
# This is a temporary hack.

cvs:
	libtoolize --copy --force --automake --ltdl
	rm -rf lightning
	lightningize --copy --force --automake
	aclocal -I .
	autoconf
	automake --add-missing
	cd libltdl; aclocal; autoconf; automake --add-missing

.PHONY: cvs
