#!/bin/sh

PATH=/opt/alice-devel/bin:$PATH

INFILE=$1
BASEFILE=`basename $INFILE .ante`
OUTFILE=$BASEFILE.ant
AMLFILE=$BASEFILE.aml

echo >$AMLFILE
echo >>$AMLFILE 'import "Ante"'
echo >>$AMLFILE 'import "Instructions"'
echo >>$AMLFILE 'open Ante'
cat $INFILE >>$AMLFILE
echo >>$AMLFILE ';Instructions.output ignore (TextIO.stdOut, compile ant);'
echo >>$AMLFILE 'OS.Process.exit OS.Process.success : unit;'

alicec $AMLFILE
alicerun $BASEFILE >$OUTFILE
rm $AMLFILE
