structure PervasiveType = MakePervasiveType(val labid_false	= "false"
					    val labid_true	= "true"
					    val labid_nil	= "nil"
					    val labid_cons	= "::"
					    val typid_bool	= "bool"
					    val typid_list	= "list"
					    val typid_int	= "int"
					    val typid_word	= "word"
					    val typid_real	= "real"
					    val typid_char	= "char"
					    val typid_string	= "string"
					    val typid_vec	= "vector"
					    val typid_array	= "array"
					    val typid_ref	= "ref"
					    val typid_exn	= "exn"
					    val typid_time	= "time"
					    val typid_prom	= "promise"
					    val valid_match	= "Match"
					    val valid_bind	= "Bind"
					    val modid_pervasive	= "__pervasive"
					   )
