SOURCES=IntInf.aml Alt.aml String.aml Bool.aml General.aml Option.aml IEEEReal.aml Integer.aml Char.aml Byte.aml List.aml Array.aml Vector.aml Pair.aml Array2.aml Ref.aml ListPair.aml VectorPair.aml Real.aml Word.aml Word32.aml Word8.aml ArraySlice.aml

-include ../../AliceMakefile
