CXX = g++
CXXFLAGS = \
	-DDEBUG_CHECK -Wall -W -Wpointer-arith -Wbad-function-cast \
	-Wcast-qual -Wstrict-prototypes -Wmissing-prototypes \
	-Wmissing-declarations -Wnested-externs -Wsynth -Winline \
	-Wno-unused -Wno-reorder -Wno-uninitialized -Wno-sign-compare

#-DINTERFACE -m486 -finline-functions -fno-implement-inlines -O6
