SOURCES = ClientMain.aml Gui.aml GUI-sig.aml GTKBUILDER-sig.aml GtkBuilder.aml ArenaWidget.aml ARENAWIDGET-sig.aml Client.aml windows/ConnectionWindow.aml windows/MainWindow.aml

ROOT = ClientMain

-include ../AliceMakefile

