//
// Author:
//   Christian Mueller <cmueller@ps.uni-sb.de>
//
// Copyright:
//   Christian Mueller, 2005
//
// Last Change:
//   $Date$ by $Author$
//   $Revision$
//

// instruction definition
// be careful that they are lexicographically ordered; otherwise the ByteCode
// Assembler won't work

INSTR(await)
INSTR(bci_call)
INSTR(bci_call0)
INSTR(bci_call1)
INSTR(bci_call2)
INSTR(bci_call3)
INSTR(bci_call_direct0)
INSTR(bci_call_direct1)
INSTR(bci_call_direct2)
INSTR(bci_call_direct3)
INSTR(bci_tailcall)
INSTR(bci_tailcall0)
INSTR(bci_tailcall1)
INSTR(bci_tailcall2)
INSTR(bci_tailcall3)
INSTR(bci_tailcall_direct0)
INSTR(bci_tailcall_direct1)
INSTR(bci_tailcall_direct2)
INSTR(bci_tailcall_direct3)
INSTR(bigtagtest)
INSTR(bigtagtest1)
INSTR(cbigtagtest)
INSTR(cbigtagtest_direct)
INSTR(ccc1)
INSTR(cccn)
INSTR(citest)
INSTR(contest)
INSTR(ctagtest)
INSTR(ctagtest_direct)
INSTR(debug_msg)
INSTR(iadd)
INSTR(ijump_eq)
INSTR(init_bigtagval)
INSTR(init_closure)
INSTR(init_con)
INSTR(init_polyrec)
INSTR(init_tagval)
INSTR(init_tup)
INSTR(init_vec)
INSTR(inlined_future_byneed)
INSTR(inlined_hole_fill)
INSTR(inlined_hole_hole)
INSTR(install_handler)
INSTR(isub)
INSTR(itest)
INSTR(jump)
INSTR(lazyselect_polyrec)
INSTR(load_bigtagval)
INSTR(load_cell)
INSTR(load_con)
INSTR(load_global)
INSTR(load_immediate)
INSTR(load_int)
INSTR(load_local)
INSTR(load_reg)
INSTR(load_tagval)
INSTR(load_vec)
INSTR(load_zero)
INSTR(loop)
INSTR(mk_closure)
INSTR(new_bigtagval)
INSTR(new_cell)
INSTR(new_con)
INSTR(new_polyrec)
INSTR(new_tagval)
INSTR(new_tup)
INSTR(new_vec)
INSTR(prepare_con)
INSTR(raise_direct)
INSTR(raise_normal)
INSTR(remove_handler)
INSTR(rjump_eq)
INSTR(rtest)
INSTR(seam_call)	
INSTR(seam_call0)	
INSTR(seam_call1)
INSTR(seam_call2)
INSTR(seam_call3)
INSTR(seam_call_prim)
INSTR(seam_call_prim0)
INSTR(seam_call_prim1)
INSTR(seam_call_prim2)
INSTR(seam_ccc1)
INSTR(seam_ccc1_wildcard)
INSTR(seam_cccn)
INSTR(seam_load_sreg)	// load scheduler register
INSTR(seam_return)	
INSTR(seam_return1)
INSTR(seam_return2)
INSTR(seam_return3)
INSTR(seam_return4)
INSTR(seam_set_nargs)
INSTR(seam_set_sreg)
INSTR(seam_tailcall)
INSTR(seam_tailcall0)
INSTR(seam_tailcall1)
INSTR(seam_tailcall2)
INSTR(seam_tailcall3)
INSTR(seam_tailcall_prim)
INSTR(seam_tailcall_prim0)
INSTR(seam_tailcall_prim1)
INSTR(seam_tailcall_prim2)
INSTR(select_tup)
INSTR(select_tup0)
INSTR(select_tup1)
INSTR(select_tup2)
INSTR(self_tailcall)
INSTR(self_tailcall1)
INSTR(self_tailcall2)
INSTR(self_tailcall3)
INSTR(self_tailcall_direct1)
INSTR(self_tailcall_direct2)
INSTR(self_tailcall_direct3)
INSTR(set_cell)
INSTR(set_global)
INSTR(set_local)
INSTR(sjump_eq)
INSTR(spec_closure)   
INSTR(stest)
INSTR(tagtest)
INSTR(tagtest1)
INSTR(vectest)
