SOURCES=TRANSACTIONAL_ARRAY2-sig.aml MkTransactionalArray2.aml ARENA-sig.aml Arena.aml IMP_QUEUE-sig.aml ImpQueue.aml SNAKE-sig.aml Snake.aml PSTATE-sig.aml PState.aml Server.aml CHANNEL-sig.aml Channel.aml READ_WRITE_LOCK-sig.aml ReadWriteLock.aml Config.aml CONFIG-sig.aml HighscoreIO.aml HIGHSCORE_IO-sig.aml DYNARRAY-sig.aml DynArray.aml



-include ../AliceMakefile
