SOURCES = CONFIG-sig.aml Config.aml ARENA-sig.aml Arena.aml PARTICIPANT-sig.aml Participant.aml SERVER-sig.aml Server.aml SNAKE-sig.aml Snake.aml HIGHSCORE_IO-sig.aml HighscoreIO.aml IMP_QUEUE-sig.aml ImpQueue.aml

ROOT = Main

-include ../AliceMakefile

