SOURCES = CONFIG-sig.aml Config.aml ARENA-sig.aml Arena.aml PARTICIPANT-sig.aml Participant.aml SERVER-sig.aml Server.aml SNAKE-sig.aml Snake.aml DummyClient.aml HIGHSCORE_IO-sig.aml HighscoreIO.aml

ROOT = Main

-include ../AliceMakefile

