Debug.alc: \

Utils.alc: \

Common.alc: \

INTERFACE-sig.alc: \

ENGINE-sig.alc: \

MkEngine.alc: \
	Debug.alc \
	Utils.alc \
	INTERFACE-sig.alc \
	ENGINE-sig.alc \

Test.alc: \
	Common.alc \
	Debug.alc \
	MkEngine.alc

