all:
	(cd common; make)
	(cd server; make)
	(cd client/windows; make)
	(cd client; make)

clean:
	(cd common; make clean)
	(cd server; make clean)
	(cd client/windows; make clean)
	(cd client; make clean)

depend:
	(cd common; make depend)
	(cd server; make depend)
	(cd client/windows; make depend)
	(cd client; make depend)

