SOURCES = Color.aml Highscore-prepare.aml HIGHSCORE-sig.aml COLOR-sig.aml POS-sig.aml Pos.aml Protocol.aml Log.aml ISpawn.aml

ROOT = Main

all:	components

Highscore.ozf:	Color.ozf

-include ../AliceMakefile

