SOURCES = Color-prepare.aml Highscore.aml HIGHSCORE-sig.aml COLOR-sig.aml POS-sig.aml Pos.aml Protocol.aml Log.aml MkHeap.aml HEAP-sig.aml

ROOT = Main

all:	components

## adding some dependencies manually
Color.ozf:	Color-prepare.aml

-include ../AliceMakefile

