all:
	(cd fundamental; make)
	(cd system; make)
	(cd data; make)
	(cd compiler; make)
	(cd regression; make)
clean:
	(cd fundamental; make clean)
	(cd system; make clean)
	(cd data; make clean)
	(cd compiler; make clean)
	(cd regression; make clean)
depend:
	(cd fundamental; make depend)
	(cd system; make depend)
	(cd data; make depend)
	(cd compiler; make depend)
	(cd regression; make depend)