all:
	(cd test; make)
	(cd fundamental; make)
	(cd system; make)
	(cd compiler; make)
clean:
	(cd test; make clean)
	(cd fundamental; make clean)
	(cd system; make clean)
	(cd compiler; make clean)
depend:
	(cd test; make depend)
	(cd fundamental; make depend)
	(cd system; make depend)
	(cd compiler; make depend)