#!/bin/sh

if [ $# -gt 1 ]
then
    echo 'usage: '$0' <count>' 1>&2
    exit 2
fi

if [ $# -ne 1 ]
then
    n=999999
else
    n=$1
fi

i=0
for src in `cat sources`
do
    if [ $i -lt $n ]
    then
	echo '(* src #' $i $src '*)'
	cat $src
	i=`expr $i + 1`
    fi
done

exit 0
