#!/bin/sh

if [ $# -ne 1 ]
then
    echo 'usage: '$0' <count>' 1>&2
    exit 2
fi

i=0
for src in `cat sources`
do
    if [ $i -lt $1 ]
    then
	echo '(* src #' $i '*)'
	cat $src
	i=`expr $i + 1`
    fi
done

exit 0
