#!/bin/sh

howcalled=$0
runmedir=`dirname $howcalled`

if test -z "${OZHOME}"
then
    IFS=:
    for i in $PATH
    do
	if test -x $i/oz
	then
	    dir=`dirname $i`
	    OZHOME=`(cd $dir; cd ..; /bin/pwd)`
	fi
    done
fi

: ${OZHOME=/usr/lib/mozart}
: ${OZ_LOAD=cache=$OZHOME/cache/}

OZ_LOAD=cache=$runmedir/:$OZ_LOAD

export OZHOME OZ_LOAD

exec ozengine Linked.ozf $1
