Debug.alc:

Path.alc:

Policy.alc: \
	Debug.alc

SPACENODE-sig.alc: \
	Path.alc

MkSpaceNode.alc: \
	Debug.alc \
	Policy.alc \
	SPACENODE-sig.alc \
	Path.alc

TREENODE-sig.alc: \
	Path.alc \
	Debug.alc

MkTreeNode.alc: \
	Policy.alc \
	TREENODE-sig.alc \
	MkSpaceNode.alc

SEARCH-sig.alc: \

MkSearch.alc: \
	Path.alc \
	SEARCH-sig.alc \
	Policy.alc \
	Debug.alc \
	MkTreeNode.alc \
	Policy.alc

Test.alc: \
	Debug.alc \
	MkSearch.alc \
	MkSearch.alc

