Debug.alc:

Path.alc:

PROBLEM-sig.alc: \
	Debug.alc

SPACENODE-sig.alc: \
	Path.alc

MkSpaceNode.alc: \
	Debug.alc \
	PROBLEM-sig.alc \
	SPACENODE-sig.alc \
	Path.alc

TREENODE-sig.alc: \
	Path.alc \
	Debug.alc

MkTreeNode.alc: \
	PROBLEM-sig.alc \
	TREENODE-sig.alc \
	MkSpaceNode.alc

SEARCH-sig.alc: \
	Path.alc

MkSearch.alc: \
	Path.alc \
	SEARCH-sig.alc \
	PROBLEM-sig.alc \
	Debug.alc \
	MkTreeNode.alc

Test.alc: \
	Debug.alc \
	MkSearch.alc

