Debug.stc:

MKSPACENODE-sig.stc: \
	Debug.stc

MkSpaceNode.stc: \
	Debug.stc \
	MKSPACENODE-sig.stc \
	MKSPACENODE-sig.stc \

SPACENODE-sig.stc: \

SpaceNode.stc: \
	Debug.stc \
	SPACENODE-sig.stc \
	MkSpaceNode.stc

MKTREENODE-sig.stc: \
	MKSPACENODE-sig.stc

MkTreeNode.stc: \
	MKTREENODE-sig.stc \
	MKTREENODE-sig.stc \
	MkSpaceNode.stc

TREENODE-sig.stc: \

TreeNode.stc: \
	TREENODE-sig.stc \
	SpaceNode.stc

Test.stc: \
	Debug.stc \
	MkTreeNode.stc \
	TreeNode.stc

