SOURCES =  ConnectionWindow.aml MainWindow.aml PlayerSettingsWindow.aml \
QuestionWindow.aml ServerSettingsWindow.aml TextWindow.aml WaitWindow.aml \
ARENAWIDGET-sig.aml ArenaWidget.aml

ROOT = Main

-include ../../AliceMakefile

