SOURCES =  Connection.aml MainWindow.aml PlayerSettings.aml \
QuestionWindow.aml ServerSettings.aml TextWindow.aml Wait.aml \
ARENAWIDGET-sig.aml ArenaWidget.aml

ROOT = Main

-include ../../AliceMakefile

