SOURCES =  Connection.aml Main.aml PlayerSettings.aml \
Question.aml ServerSettings.aml Text.aml Wait.aml \
ARENAWIDGET-sig.aml ArenaWidget.aml EnterName.aml GtkSupport.aml \
Error.aml RADARWIDGET-sig.aml RadarWidget.aml

ROOT = Main

-include ../../AliceMakefile

