structure Prebound = MakePrebound(val valid_false	= "false"
				  val valid_true	= "true"
				  val valid_nil		= "nil"
				  val valid_cons	= "::"
				  val valid_ref		= "ref"
				  val valid_match	= "Match"
				  val valid_bind	= "Bind"

				  val typid_bool	= "bool"
				  val typid_int		= "int"
				  val typid_word	= "word"
				  val typid_real	= "real"
				  val typid_string	= "string"
				  val typid_char	= "char"
				  val typid_list	= "list"
				  val typid_vec		= "vector"
				  val typid_ref		= "ref"
				  val typid_exn		= "exn"
				 )
