#!/bin/sh

tarname=helikopter.tar.gz
sources="Color.sml Geometry.sml Lexer.lex Machine.sml Main.sml PPMFile.sml Parser.grm RENDERER.sml Renderer.sml build.sml sources.cm"
files="README buildme runme src"

tar -czf $tarname $files
md5sum $tarname
