# -*-makefile-*-

#VERSION		=
#PKG_NAME	= lewinsky-disaster-$(VERSION)
#PKG_MOGUL_URI	= mogul:/clinton/lewinsky
#PKG_URI		= x-ozlib://clinton/monica
#PKG_SOURCES	=
#PKG_INSTALLS	=
#PKG_UPDATE	= tgz tarz
#PKG_INSTALLS_DOC=

