#!/bin/sh

howcalled=$0

if test -z "${STOCKHOME}"
then
  dir=`dirname $howcalled`
  STOCKHOME=`(cd $dir; cd ..; /bin/pwd)`
fi

: ${OZHOME=/opt/mozart-devel}
: ${OZ_LOAD=cache=$OZHOME/cache/}

PATH=$OZHOME/bin:$STOCKHOME/bin:$PATH

ALICE_LOAD=pattern='?{x}'='?{x}':pattern='?{x}'='?{x}.ozf':pattern=x-alice\\:/'?{x}'.ozf=$STOCKHOME/'?{x}'.ozf:pattern=x-alice\\:/'?{x}'=$STOCKHOME/'?{x}'.ozf

OZ_LOAD=$ALICE_LOAD:$OZ_LOAD

export STOCKHOME PATH OZ_LOAD ALICE_LOAD

exec ozengine x-alice:/VMMain "$@"
