#!/bin/sh

howcalled=$0

if test -z "${STOCKHOME}"
then
  dir=`dirname $howcalled`
  STOCKHOME=`(cd $dir; cd ..; /bin/pwd)`
fi

: ${OZHOME=/opt/mozart-1.2.1}
: ${OZ_LOAD=cache=$OZHOME/cache/}

PATH=$OZHOME/bin:$STOCKHOME/bin:$PATH
OZ_LOAD=pattern='?{x}'='?{x}.ozf':pattern=x-alice\\:/'?{x}'=$STOCKHOME/'?{x}'.ozf:pattern=x-alice\\:/'?{x}'=$STOCKHOME/'?{x}':$OZ_LOAD

export STOCKHOME PATH OZ_LOAD

exec ozengine x-alice:/VMMain "$@"
