#!/bin/sh

howcalled=$0

if test -z "${STOCKHOME}"
then
  dir=`dirname $howcalled`
  STOCKHOME=`(cd $dir; cd ..; /bin/pwd)`
fi

: ${OZHOME=/opt/mozart-1.2.0}
: ${OZ_LOAD=cache=$OZHOME/cache/}

OZ_LOAD=pattern='?{x}'='?{x}.ozf':pattern=x-alice\\:/'?{x}'=$STOCKHOME/'?{x}'.ozf:$OZ_LOAD

export STOCKHOME OZ_LOAD

#--** note: the `--execheader' option in the next line is a hack
exec "$STOCKHOME/bin/alicerun" "$OZHOME/bin/ozl" --execheader alicerun "$@"
