#!/bin/sh

OZHOME=/opt/mozart-1.1.1

howcalled=$0

if test -z "${STOCKHOME}"
then
  dir=`dirname $howcalled`
  STOCKHOME=`(cd $dir; cd ..; /bin/pwd)`
fi

PATH=$OZHOME/bin:$STOCKHOME/bin:$PATH

if test -z "${OZ_LOAD}"
then
  OZ_LOAD=cache=$OZHOME/cache/
fi

OZ_LOAD=pattern='?{x}'='?{x}.ozf':pattern=x-alice\\:/'?{x}'=$STOCKHOME/'?{x}'.ozf:pattern=x-alice\\:/'?{x}'=$STOCKHOME/'?{x}':$OZ_LOAD

export STOCKHOME PATH OZ_LOAD

exec ozengine x-alice:/StowMain "$@"
