#!/bin/bash

# check PKG_CONFIG_PATH
if ! pkg-config gtk+-2.0 libgnomecanvas-2.0 >& /dev/null ; then
  echo "** 'pkg-config gtk+-2.0 libgnomecanvas-2.0' failed!"
  echo "** Either GTK+ and GnomeCanvas are not installed,"
  echo "** or the PKG_CONFIG_PATH variable is not set to the"
  echo "** appropriate ..../lib/pkgconfig path."
  exit 1 ;
fi

# try to find out platform
case `uname -s` in
    CYGWIN*) WINDOWS=1 ;;
esac

case $1 in
    --windows)    WINDOWS=1 ;;
    --no-windows) WINDOWS= ;;
esac

if test "$WINDOWS" ; then
    echo "BUILD_ALL: Win32 platform detected; override with --no-windows." ;
fi

(make generate             WINDOWS=$WINDOWS && 
 make depend               WINDOWS=$WINDOWS && 
 make compile sample-files WINDOWS=$WINDOWS)

