#!/bin/bash

PC_OPTS="gtk+-2.0 libgnomecanvas-2.0"

if test "$GTK_PREFIX" ; then
  echo "BUILD_ALL: Using GTK library root prefix: $GTK_PREFIX."
  export PKG_CONFIG_PATH=$GTK_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
  export PATH=$GTK_PREFIX/bin:$GTK_PREFIX/lib:$PATH
  PC_OPTS="$PC_OPTS --define-variable=prefix=$GTK_PREFIX" ;
fi

# check libs
if ! pkg-config --print-errors --exists $PC_OPTS ; then
  exit 1 ;
fi

# try to find out platform
case `uname -s` in
    CYGWIN*) WINDOWS=1 ;;
esac

case $1 in
    --windows)    WINDOWS=1 ;;
    --no-windows) WINDOWS= ;;
esac

if test "$WINDOWS" ; then
    echo "BUILD_ALL: Win32 platform detected; override with --no-windows." ;
fi

(make generate             WINDOWS=$WINDOWS "PC_OPTS=$PC_OPTS" && 
 make depend               WINDOWS=$WINDOWS "PC_OPTS=$PC_OPTS" && 
 make compile sample-files WINDOWS=$WINDOWS "PC_OPTS=$PC_OPTS" )

