URL = http://www.ps.uni-sb.de/alice/download/sources

REVISION = 1
PACKAGES = seam-1.2 alice-1.2 \
	alice-gecode-1.2 alice-gtk-1.2 \
	alice-xml-1.2 alice-sqlite-1.2 alice-regex-1.2 \
	alice-runtime-1.2

all: $(PACKAGES:%=%.tar.gz)

$(PACKAGES:%=%.tar.gz): %:
	curl $(URL)/$@ -o $@
	tar -f $@ -z -x '*/debian/*.spec' -O > $(@:%.tar.gz=%)-$(REVISION).spec
	./build-rpm $@ $(@:%.tar.gz=%)-$(REVISION).spec

complete:
	./build-rpm $(PACKAGES:%=%.tar.gz) alice-complete.spec
