structure Abbrev  =
    struct
	val CBind          = ("de/uni_sb/ps/dml/runtime/DMLConstants/dmlbind","de/uni_sb/ps/dml/runtime/DMLName")
	val CCons          = ("de/uni_sb/ps/dml/builtin/DMLConstants/cons","de/uni-sb/ps/dml/runtime/DMLConstructor")
	val CFalse         = ("de/uni_sb/ps/dml/builtin/DMLConstants/dmlfalse","de/uni_sb/ps/dml/runtime/DMLName")
	val CMatch         = ("de/uni_sb/ps/dml/runtime/DMLConstants/dmlmatch","de/uni_sb/ps/dml/runtime/DMLName")
	val CNil          = ("de/uni_sb/ps/dml/builtin/DMLConstants/dmlnil","de/uni_sb/ps/dml/runtime/DMLName")
	val CPickle        = ("de/uni_sb/ps/dml/builtin/General/pickle", "de/uni_sb/ps/dml/builtin/General$Pickle")
	val CTrue          = ("de/uni_sb/ps/dml/builtin/DMLConstants/dmltrue","de/uni_sb/ps/dml/runtime/DMLName")
	val CUnit          = ("de/uni_sb/ps/dml/runtime/DMLConstants/dmlunit","de/uni_sb/ps/dml/runtime/DMLName")
	val CName          = "de/uni_sb/ps/dml/runtime/DMLName"
	val CConstants     = "de/uni_sb/ps/dml/runtime/DMLConstants"
	val CConstructor   = "de/uni_sb/ps/dml/runtime/DMLConstructor"
	val CConVal        = "de/uni_sb/ps/dml/runtime/DMLConVal"
	val CExWrap        = "de/uni_sb/ps/dml/runtime/DMLExceptionWrapper"
	val CFcnClosure    = "de/uni_sb/ps/dml/runtime/DMLFunction"
	val CFuture        = "de/uni_sb/ps/dml/runtime/DMLFuture"
	val CInt           = "de/uni_sb/ps/dml/runtime/DMLInt"
	val CInternalError = "de/uni_sb/ps/dml/runtime/DMLInternalError"
	val CLabel         = "de/uni_sb/ps/dml/runtime/DMLLabel"
	val CLVal          = "de/uni_sb/ps/dml/runtime/DMLLVal"
	val CReal          = "de/uni_sb/ps/dml/runtime/DMLReal"
	val CRecord        = "de/uni_sb/ps/dml/runtime/DMLRecord"
	val CRecordArity   = "de/uni_sb/ps/dml/runtime/DMLRecordArity"
	val CReference     = "de/uni_sb/ps/dml/runtime/DMLReference"
	val CSCon          = "de/uni_sb/ps/dml/runtime/DMLSCon"
	val CStr           = "de/uni_sb/ps/dml/runtime/DMLString"
	val CDMLThread     = "de/uni_sb/ps/dml/runtime/DMLThread"
	val CTuple         = "de/uni_sb/ps/dml/runtime/DMLTuple"
	val CVal           = "de/uni_sb/ps/dml/runtime/DMLValue"
	val CHashtable     = "java/util/Hashtable"
	val CObj           = "java/lang/Object"
	val CString        = "java/lang/String"
	val CThread        = "java/lang/Thread"
	val CVector        = "java/util/Vector"
	val CPlus          = ("de/uni_sb/ps/dml/builtin/Primitives/primitive_plus","de/uni_sb/ps/dml/builtin/Plus")
	val CEquals        = ("de/uni_sb/ps/dml/builtin/Primitives/primitive_equals","de/uni_sb/ps/dml/builtin/Equals")
	val CNot           = ("de/uni_sb/ps/dml/builtin/Primitives/primitive_not","de/uni_sb/ps/dml/builtin/Not")
	val CDeref         = ("de/uni_sb/ps/dml/builtin/Primitives/primitive_deref","de/uni_sb/ps/dml/builtin/Deref")
	val CRef           = ("de/uni_sb/ps/dml/DMLBuiltin/Primitives/primitive_ref","de/uni_sb/ps/dml/DMLBuiltin/Ref")
	val CAssign        = ("de/uni_sb/ps/dml/DMLBuiltin/Primitives/primitive_assign","de/uni_sb/ps/dml/DMLBuiltin/Assign")
	val CIntFromString = ("de/uni_sb/ps/dml/DMLBuiltin/Primitives/primitive_intfromstring","de/uni_sb/ps/dml/DMLBuiltin/IntFromString")
	val CBoolFromString = ("de/uni_sb/ps/dml/DMLBuiltin/Primitives/primitive_boolfromstring","de/uni_sb/ps/dml/DMLBuiltin/BoolFromString")
	val CRealFromString = ("de/uni_sb/ps/dml/DMLBuiltin/Primitives/primitive_realfromstring","de/uni_sb/ps/dml/DMLBuiltin/RealFromString")
	val CSel            = "de/uni_sb/ps/dml/DMLBuiltin/Sel"
    end
