## -*- Makefile -*-
##
## Author:
##   Leif Kornstaedt <kornstae@ps.uni-sb.de>
## 
## Copyright:
##   Leif Kornstaedt, 2000-2003
## 
## Last change:
##   $Date$ by $Author$
##   $Revision$
## 

SEAMTOOL = seamtool

ifeq ($(WINDOWS), 1)
EXTRA_LDFLAGS = --image-base=1010000
LIBS = -lwsock32
else
EXTRA_LDFLAGS = 
LIBS = -lm
endif

INCLUDES = -I.

CXX = $(SEAMTOOL) c++
LD = $(SEAMTOOL) ld

MAKEDEPEND = $(SEAMTOOL) makedepend $(INCLUDES)
